// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DontCopyAlways
{
    internal sealed partial class Vsix
    {
        public const string Id = "DontCopyAlways.d38e1a6d-0c1c-4aab-bf12-2cc84406b005";
        public const string Name = "Don't Copy Always";
        public const string Description = @"Check for files that have 'Copy to output directory' set to 'Copy always'.";
        public const string Language = "en-US";
        public const string Version = "1.5.8";
        public const string Author = "Matt Lacey";
        public const string Tags = "";
    }
}
